; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\b5020045\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
